# secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:jatt-singh/transaction-api-sre-assessment.git
  sshPrivateKey: |
# add you ssh private key here