apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: us-east4
          clusterName:  gke-app-us-east4-cluster
          serviceAccountRef:
            name: external-secret-external-secrets
            namespace: external-secret
      projectID: solid-authority-470915-b7
