apiVersion: v2
appVersion: v2.13.1
kubeVersion: ">=1.25.0-0"
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 7.7.6
home: https://github.com/argoproj/argo-helm
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.7.6
