argo-cd:
  configs:
    params:
      server.insecure: true
      controller.diff.server.side: true
    cm:
      exec.enabled: "true"
    rbac:
      policy.csv: |
        p, role:admin, exec, *, */*, allow
  server:
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        acme.cert-manager.io/http01-edit-in-place: "true"
        cert-manager.io/acme-challenge-type: http01
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/issue-temporary-certificate: "true"
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
        nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE, PATCH
        nginx.ingress.kubernetes.io/cors-allow-origin: '*'
        nginx.ingress.kubernetes.io/cors-max-age: "1728000"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/proxy-real-ip-cidr: 0.0.0.0/0
        nginx.ingress.kubernetes.io/real-ip-header: CF-Connecting-IP
        nginx.ingress.kubernetes.io/upstream-hash-by: $remote_addr
        nginx.ingress.kubernetes.io/upstream-hash-by-subset: "false"
        nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
      controller: generic
      ingressClassName: nginx
      hostname: argocd.test.xyz